    # Generated by Django 4.0.2 on 2022-03-16 04:10

    from django.conf import settings
    from django.db import migrations, models
    import django.db.models.deletion
    import django.db.models.manager


    class Migration(migrations.Migration):

        initial = True

        dependencies = [
            ('baner', '0001_initial'),
            migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ]

        operations = [
            migrations.CreateModel(
                name='Brand',
                fields=[
                    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('name', models.CharField(max_length=50, verbose_name='Бренд')),
                    ('icon', models.FileField(upload_to='brand_icon/', verbose_name='Иконка бренда')),
                    ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ],
                options={
                    'verbose_name': 'Бренд',
                    'verbose_name_plural': 'Бренды',
                },
            ),
            migrations.CreateModel(
                name='Caps',
                fields=[
                    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('name', models.CharField(max_length=250, verbose_name='Названия')),
                    ('price', models.IntegerField()),
                    ('description', models.TextField(verbose_name='Описания')),
                    ('is_available', models.BooleanField(default=True, verbose_name='в Наличии')),
                    ('new_price', models.IntegerField(blank=True, null=True)),
                    ('created_data', models.DateField(auto_now_add=True)),
                    ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='caps.brand', verbose_name='Имя бренда')),
                    ('in_baner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caps', to='baner.baner')),
                ],
                options={
                    'verbose_name': 'Кепка',
                    'verbose_name_plural': 'Кепки',
                },
                managers=[
                    ('available', django.db.models.manager.Manager()),
                ],
            ),
            migrations.CreateModel(
                name='Sizes',
                fields=[
                    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('value', models.CharField(max_length=2, verbose_name='Значение')),
                ],
                options={
                    'verbose_name': 'Размеры',
                    'verbose_name_plural': 'Размеры',
                },
            ),
            migrations.CreateModel(
                name='UserCapsFavorite',
                fields=[
                    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('is_favorite', models.BooleanField(default=True, verbose_name='Избранные')),
                    ('caps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caps.caps', verbose_name='Кепки')),
                    ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ],
                options={
                    'verbose_name': 'Избранный',
                    'verbose_name_plural': 'Избранные',
                },
            ),
            migrations.CreateModel(
                name='CapsImage',
                fields=[
                    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('image', models.ImageField(upload_to='caps_foto/', verbose_name='Изображение')),
                    ('caps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capsimage', to='caps.caps', verbose_name='Кепки')),
                ],
                options={
                    'verbose_name': 'Фотографии кепок',
                    'verbose_name_plural': 'Фотографии кепок',
                },
            ),
            migrations.AddField(
                model_name='caps',
                name='size',
                field=models.ManyToManyField(related_name='sizes', to='caps.Sizes', verbose_name='Размер'),
            ),
            migrations.CreateModel(
                name='Basket',
                fields=[
                    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('quantity', models.IntegerField()),
                    ('created_at', models.DateTimeField(auto_now_add=True)),
                    ('updated_at', models.DateTimeField(auto_now=True)),
                    ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caps.caps')),
                    ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caps.sizes')),
                    ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ],
                options={
                    'verbose_name': 'Корзина',
                    'verbose_name_plural': 'Корзина',
                },
            ),
        ]
