# Generated by Django 4.0.2 on 2022-03-16 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indigit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capsindigit',
            options={'verbose_name': 'Кепки в цифрах', 'verbose_name_plural': 'Кепки в цифрах'},
        ),
    ]
